
export const privacyPolicyText = `
POLÍTICA DE PRIVACIDADE E TERMOS DE USO – STUDYRATS
Lei nº 13.709/2018 – Lei Geral de Proteção de Dados (LGPD)

1. Identificação do Projeto
   O StudyRats é um aplicativo mobile desenvolvido no contexto acadêmico da disciplina de Engenharia de Software da Universidade Federal de Campina Grande (UFCG), com a finalidade de incentivar hábitos de estudo por meio de mecanismos de gamificação, registro de sessões de estudo, criação de grupos, acompanhamento de desempenho, ranking entre usuários e interação social por meio de comentários e reações. O projeto possui caráter acadêmico e educacional, sendo desenvolvido por equipe discente sob orientação docente. Para os fins da Lei Geral de Proteção de Dados, considera-se como Controlador dos dados a equipe responsável pelo desenvolvimento do projeto StudyRats, vinculada à UFCG.

2. Dados Pessoais Coletados
   O StudyRats poderá coletar dados pessoais fornecidos diretamente pelo usuário no momento do cadastro ou durante a utilização da plataforma, bem como dados coletados automaticamente pelo sistema. Entre os dados fornecidos pelo usuário estão nome, endereço de e-mail, senha armazenada mediante técnicas seguras de hash criptográfico, foto de perfil opcional, informações registradas nas sessões de estudo como título, descrição, duração e categoria, imagens enviadas como comprovação de atividade, comentários publicados, reações em postagens e demais conteúdos inseridos voluntariamente na plataforma. Também poderão ser coletados dados automaticamente, tais como endereço IP, data e horário de acesso, informações técnicas do dispositivo utilizado, sistema operacional, versão do aplicativo e registros de autenticação e navegação, com a finalidade de garantir segurança, estabilidade e melhoria contínua do serviço. O StudyRats não realiza coleta intencional de dados pessoais sensíveis, nos termos da LGPD, salvo se eventualmente fornecidos pelo próprio usuário em campos de texto livre, hipótese em que o tratamento seguirá as regras legais aplicáveis.

3. Finalidade do Tratamento dos Dados
   Os dados pessoais coletados são utilizados para permitir o cadastro e autenticação de usuários, viabilizar o acesso às funcionalidades da plataforma, registrar sessões de estudo, gerar estatísticas individuais e coletivas, calcular rankings e sequências de dias estudados (streaks), possibilitar a criação e administração de grupos, permitir a interação entre usuários por meio de comentários e reações, garantir a segurança da aplicação, prevenir fraudes e acessos indevidos, melhorar a experiência do usuário e cumprir obrigações legais previstas na legislação brasileira. O tratamento é realizado de maneira compatível com as finalidades informadas, observando os princípios da finalidade, adequação, necessidade, transparência, segurança e prevenção previstos na LGPD.

4. Base Legal para o Tratamento
   O tratamento de dados pessoais no âmbito do StudyRats fundamenta-se nas hipóteses legais previstas na Lei nº 13.709/2018, especialmente na execução de contrato ou de procedimentos preliminares relacionados ao contrato, considerando que o uso do aplicativo depende do tratamento de dados para sua operacionalização; no consentimento do titular, quando necessário; no cumprimento de obrigação legal ou regulatória; e no legítimo interesse do controlador, sempre respeitados os direitos e liberdades fundamentais do titular e observada a proporcionalidade entre a finalidade e o tratamento realizado.

5. Compartilhamento de Dados
   Os dados pessoais dos usuários não são vendidos, comercializados ou repassados a terceiros para fins publicitários. O compartilhamento poderá ocorrer apenas quando necessário para viabilizar o funcionamento técnico da aplicação, como no uso de serviços de hospedagem, banco de dados, envio de e-mails ou infraestrutura tecnológica, bem como em caso de obrigação legal, requisição de autoridade competente ou ordem judicial. Em todas as hipóteses de compartilhamento, serão adotadas medidas técnicas e contratuais adequadas para assegurar a proteção, confidencialidade e integridade das informações.

6. Armazenamento e Segurança
   O StudyRats adota medidas técnicas e administrativas apropriadas para proteger os dados pessoais contra acessos não autorizados, destruição, perda, alteração ou qualquer forma de tratamento inadequado ou ilícito. Entre as medidas adotadas estão a utilização de criptografia na transmissão de dados por meio de protocolo HTTPS, armazenamento seguro de senhas com uso de hash criptográfico, controle de acesso restrito ao banco de dados, monitoramento de logs de acesso e atualização periódica das ferramentas utilizadas no desenvolvimento do sistema. Os dados pessoais serão mantidos apenas pelo tempo necessário para cumprir as finalidades para as quais foram coletados ou para atender exigências legais, sendo posteriormente eliminados ou anonimizados, quando possível.

7. Direitos do Titular
   Nos termos da LGPD, o titular dos dados possui o direito de solicitar a qualquer momento a confirmação da existência de tratamento, o acesso aos dados pessoais tratados, a correção de dados incompletos, inexatos ou desatualizados, a anonimização, bloqueio ou eliminação de dados desnecessários ou tratados em desconformidade com a legislação, a portabilidade dos dados, a eliminação dos dados tratados com base no consentimento, a informação sobre compartilhamento realizado e a revogação do consentimento, quando aplicável. As solicitações deverão ser encaminhadas ao canal institucional disponibilizado pela equipe do projeto, sendo analisadas no prazo legal.

8. Exclusão da Conta
   O usuário poderá solicitar a exclusão de sua conta a qualquer momento. Após a solicitação, os dados pessoais vinculados à conta serão eliminados ou anonimizados, ressalvadas hipóteses de retenção obrigatória previstas em lei. Informações relacionadas a interações coletivas, como comentários em grupos, poderão permanecer registradas de forma anonimizada, sem identificação direta do titular.

9. Dados de Menores de Idade
   Caso o aplicativo seja utilizado por menores de idade, recomenda-se a supervisão dos pais ou responsáveis. Nos casos de tratamento de dados de crianças, será exigido consentimento específico e destacado de pelo menos um dos responsáveis legais, conforme previsto na legislação. O tratamento deverá sempre observar o melhor interesse do menor.

10. Atualizações da Política
    Esta Política de Privacidade poderá ser atualizada a qualquer tempo, especialmente em razão de alterações legislativas, evolução do projeto acadêmico ou modificações nas funcionalidades do aplicativo. A versão mais recente deverá estar disponível junto à documentação oficial do sistema, sendo responsabilidade do usuário consultar periodicamente seu conteúdo.

11. Termos de Uso
    Ao realizar cadastro e utilizar o StudyRats, o usuário declara estar ciente e de acordo com os presentes Termos de Uso. O usuário compromete-se a fornecer informações verdadeiras, completas e atualizadas, sendo responsável pela guarda e sigilo de suas credenciais de acesso. É vedado utilizar a plataforma para fins ilícitos, ofensivos, discriminatórios, fraudulentos ou que violem direitos de terceiros. O usuário é responsável pelo conteúdo que publica, incluindo textos, imagens e comentários, devendo respeitar as regras de convivência e boas práticas acadêmicas. O administrador de grupos poderá moderar conteúdos e remover publicações que descumpram as regras estabelecidas. O StudyRats, por se tratar de projeto acadêmico, não garante disponibilidade contínua e ininterrupta do serviço, podendo ocorrer instabilidades decorrentes de testes, atualizações ou limitações técnicas. A equipe desenvolvedora não se responsabiliza por eventuais prejuízos decorrentes do uso inadequado da plataforma pelo usuário. A utilização do aplicativo implica aceitação integral das disposições aqui previstas.
   `;